# Generated by Django 4.2.7 on 2023-11-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('beginning_children', models.IntegerField()),
                ('new_admission', models.IntegerField()),
                ('total_strength', models.IntegerField()),
                ('reintegration', models.IntegerField()),
                ('rehabilitation', models.IntegerField()),
                ('referral', models.IntegerField()),
                ('left', models.IntegerField()),
                ('death', models.IntegerField()),
                ('end_strength', models.IntegerField()),
                ('rescue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('whom_to_see', models.CharField(max_length=255)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('signature', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
