# Generated by Django 5.1b1 on 2024-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
