# Generated by Django 5.1b1 on 2024-08-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffRecord',
        ),
    ]
