# Generated by Django 4.2.7 on 2024-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_alter_masterrecords_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecords',
            name='id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
