# Generated by Django 4.2.7 on 2023-11-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_performanceappraisal_visitorregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionplanRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_plan', models.DateField()),
                ('detailed_notes', models.TextField()),
                ('action_plan_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AwarnessRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('participants', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BpPulsenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pulse', models.IntegerField()),
                ('bp', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='case_history_photos/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('maritalStatus', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True)),
                ('identificationMark', models.CharField(blank=True, max_length=255, null=True)),
                ('educationBackground', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('residentContactNumber', models.CharField(max_length=15)),
                ('relativeOrFriendsContact', models.CharField(max_length=15)),
                ('idProofAvailable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('idProofDetails', models.CharField(blank=True, max_length=255, null=True)),
                ('policeMemoAvailable', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('policeStationDetails', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('number_of_sessions', models.IntegerField()),
                ('observation_identification', models.TextField()),
                ('signature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('complaints', models.TextField()),
                ('others', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('type_of_disease', models.CharField(max_length=100)),
                ('tablet_details', models.TextField()),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NightSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('details_of_visit', models.TextField()),
                ('number_of_rescue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupilName', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('morningAttendance', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10, null=True)),
                ('eveningAttendance', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10, null=True)),
                ('daysPresent', models.IntegerField()),
                ('schoolFee', models.CharField(max_length=255)),
                ('dayOfPayment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('resident_name', models.CharField(max_length=255)),
                ('skill_training_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SmcRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('introduction_of_meeting', models.TextField()),
                ('last_month_performance_details', models.TextField()),
                ('issue_resolved', models.BooleanField()),
                ('this_month_issue', models.TextField()),
                ('ngo_staff_name', models.CharField(max_length=255)),
                ('gcc_officials_name', models.CharField(max_length=255)),
                ('police_officials_name', models.CharField(max_length=255)),
                ('residents_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialEntertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('admission', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('workDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=255, verbose_name='SI.No')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('working_hours', models.TimeField(verbose_name='Working Hours')),
                ('days', models.IntegerField(verbose_name='Days')),
                ('working_days', models.IntegerField(verbose_name='No.of Working Days')),
                ('leave_days', models.IntegerField(verbose_name='No.of Days Leaves')),
                ('remarks', models.TextField(verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('receipt', models.CharField(max_length=255)),
                ('issued', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
