# Generated by Django 4.2.7 on 2023-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_actionplanregister_awarnessregister_bppulsenote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inmate_name', models.CharField(max_length=100)),
                ('age_gender', models.CharField(max_length=20)),
                ('accident_condition', models.CharField(max_length=200)),
                ('accident_place', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeathRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50)),
                ('name_of_the_death_person', models.CharField(max_length=100)),
                ('age_sex', models.CharField(max_length=20)),
                ('date_of_death', models.DateField()),
                ('reason_for_death', models.CharField(max_length=200)),
                ('whom_to_claim_death_person', models.CharField(max_length=100)),
                ('address_and_contact_number', models.CharField(max_length=200)),
                ('legal_producer_taken_if_unclaimed', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.CharField(max_length=20)),
                ('admission_no', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('resident_name', models.CharField(max_length=100)),
                ('employment_name', models.CharField(max_length=100)),
                ('address_and_contact_details', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('signature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rehabitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50)),
                ('admission_number', models.CharField(max_length=50)),
                ('name_of_the_resident', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField()),
                ('mode_of_rescue', models.CharField(max_length=100)),
                ('mode_of_rehabilitation', models.CharField(max_length=100)),
                ('follow_up', models.CharField(max_length=100)),
            ],
        ),
    ]
