# Generated by Django 4.2.7 on 2024-03-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_staff_userauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_UserAuth',
        ),
    ]
