# Generated by Django 4.1.12 on 2023-12-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentregister',
            name='accident_condition',
        ),
        migrations.RemoveField(
            model_name='accidentregister',
            name='accident_place',
        ),
        migrations.RemoveField(
            model_name='accidentregister',
            name='age_gender',
        ),
        migrations.RemoveField(
            model_name='accidentregister',
            name='date',
        ),
        migrations.RemoveField(
            model_name='accidentregister',
            name='inmate_name',
        ),
        migrations.RemoveField(
            model_name='accidentregister',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='accidentregister',
            name='uqid',
        ),
    ]
