# Generated by Django 4.1.12 on 2023-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_accidentregister_deathregister_employmentlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reintegration',
            name='admission_no',
            field=models.IntegerField(),
        ),
    ]
