# Generated by Django 4.1.12 on 2023-12-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_remove_accidentregister_accident_condition_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccidentRegister',
        ),
        migrations.DeleteModel(
            name='ActionplanRegister',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AwarnesRegister',
        ),
        migrations.DeleteModel(
            name='BpPulsenote',
        ),
        migrations.DeleteModel(
            name='CaseHistory',
        ),
        migrations.DeleteModel(
            name='CounsellingRegister',
        ),
        migrations.DeleteModel(
            name='DeathRegister',
        ),
        migrations.DeleteModel(
            name='EmploymentLink',
        ),
        migrations.DeleteModel(
            name='FoodMenu',
        ),
        migrations.DeleteModel(
            name='Inspectionregister',
        ),
        migrations.DeleteModel(
            name='MasterRecords',
        ),
        migrations.DeleteModel(
            name='MedicalCamp',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='NightSurvey',
        ),
        migrations.DeleteModel(
            name='PerformanceAppraisal',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.DeleteModel(
            name='provision',
        ),
        migrations.DeleteModel(
            name='Rehabitation',
        ),
        migrations.DeleteModel(
            name='Reintegration',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.DeleteModel(
            name='SalaryRegister',
        ),
        migrations.DeleteModel(
            name='SkillTraining',
        ),
        migrations.DeleteModel(
            name='SmcRegister',
        ),
        migrations.DeleteModel(
            name='SocialEntertainment',
        ),
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
        migrations.DeleteModel(
            name='StaffMovement',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='VisitorRegister',
        ),
    ]
