# Generated by Django 4.2.7 on 2023-11-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_accidentregister_deathregister_employmentlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceappraisal',
            name='month',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
