# Generated by Django 4.1.12 on 2023-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_reintegration_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendence',
            name='sno',
            field=models.IntegerField(),
        ),
    ]
