# Generated by Django 4.2.7 on 2023-11-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_performanceappraisal_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceappraisal',
            old_name='month',
            new_name='date',
        ),
    ]
