# Generated by Django 4.1.12 on 2023-11-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_staffattendence_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendence',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffattendence',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffattendence',
            name='leave_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffattendence',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffattendence',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staffattendence',
            name='working_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffattendence',
            name='working_hours',
            field=models.TimeField(),
        ),
    ]
