# Generated by Django 4.2.7 on 2023-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_rename_month_performanceappraisal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='schoolFee',
            field=models.IntegerField(),
        ),
    ]
