# Generated by Django 4.1.12 on 2023-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_alter_staffattendence_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightsurvey',
            name='date',
            field=models.DateField(max_length=255),
        ),
    ]
