# Generated by Django 4.2.7 on 2023-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_alter_resident_schoolfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=50)),
                ('date_purchase', models.DateField()),
                ('name_asset', models.CharField(max_length=100)),
                ('no_of_items', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_no', models.CharField(max_length=50)),
                ('place_asset', models.CharField(max_length=100)),
                ('owner_asset', models.CharField(max_length=100)),
                ('dispose_date', models.DateField()),
            ],
        ),
    ]
