# Generated by Django 4.2.7 on 2024-02-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_alter_masterrecords_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecords',
            name='id',
            field=models.PositiveBigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
