# Generated by Django 4.2.7 on 2024-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_alter_masterrecords_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecords',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
