# Generated by Django 4.1.12 on 2023-11-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_alter_employmentlink_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregister',
            name='sno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skilltraining',
            name='sl_no',
            field=models.IntegerField(max_length=255),
        ),
    ]
