# Generated by Django 4.2.7 on 2023-11-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_alter_bppulsenote_bp_alter_bppulsenote_sno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smcregister',
            name='issue_resolved',
            field=models.TextField(),
        ),
    ]
