# Generated by Django 4.2.7 on 2024-02-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_form_alter_record_uqid_record_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='form',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
