# Generated by Django 4.1.12 on 2023-11-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_alter_deathregister_sno_alter_skilltraining_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathregister',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
