# Generated by Django 4.2.7 on 2023-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_alter_smcregister_issue_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentlink',
            name='admission_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employmentlink',
            name='si_no',
            field=models.IntegerField(),
        ),
    ]
