# Generated by Django 4.2.7 on 2024-02-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_alter_masterrecords_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='uqid',
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
