# Generated by Django 4.2.7 on 2023-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_alter_employmentlink_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provision',
            name='balance_quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provision',
            name='total_quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provision',
            name='utilized_quantity',
            field=models.CharField(max_length=255),
        ),
    ]
