# Generated by Django 4.2.7 on 2024-02-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_remove_casehistory_uqid_alter_casehistory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightsurvey',
            name='uqid',
        ),
    ]
