# Generated by Django 4.1.12 on 2023-11-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_alter_smcregister_issue_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='policeMemoAvailable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='skilltraining',
            name='sl_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smcregister',
            name='issue_resolved',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=255),
        ),
    ]
