# Generated by Django 4.2.7 on 2023-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_alter_provision_balance_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_snacks', models.CharField(max_length=100)),
                ('no_of_resident1', models.IntegerField()),
                ('breakfast', models.CharField(max_length=100)),
                ('no_of_resident2', models.IntegerField()),
                ('lunch', models.CharField(max_length=100)),
                ('no_of_resident3', models.IntegerField()),
                ('dinner', models.CharField(max_length=100)),
                ('no_of_resident4', models.IntegerField()),
            ],
        ),
    ]
