# Generated by Django 4.2.7 on 2024-02-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_remove_stock_uqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorregister',
            name='uqid',
        ),
    ]
