# Generated by Django 4.1.12 on 2023-11-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_inspectionrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionRecord',
            new_name='SalaryRegister',
        ),
    ]
