# Generated by Django 4.2.7 on 2023-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_foodmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('sign', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
