# Generated by Django 4.2.7 on 2023-11-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0016_salaryregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='sign',
            field=models.TextField(),
        ),
    ]
