# Generated by Django 4.2.7 on 2023-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_alter_salaryregister_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_plan', models.DateField()),
                ('working_area', models.CharField(max_length=255)),
                ('nature_of_work', models.CharField(max_length=255)),
                ('work_done_by', models.CharField(max_length=255)),
                ('sign', models.CharField(max_length=255)),
            ],
        ),
    ]
