# Generated by Django 4.1.12 on 2023-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_foodmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='salary',
            field=models.ImageField(upload_to=''),
        ),
    ]
