# Generated by Django 4.2.7 on 2024-02-18 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_accidentregister_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentregister',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
