# Generated by Django 4.1.12 on 2023-11-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_alter_salaryregister_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
