# Generated by Django 4.2.7 on 2024-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_alter_accidentregister_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentregister',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
