# Generated by Django 4.2.7 on 2023-11-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_staffmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmovement',
            name='sign',
            field=models.TextField(),
        ),
    ]
