# Generated by Django 4.2.7 on 2024-02-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_alter_accidentregister_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentregister',
            options={'ordering': ['-created_at']},
        ),
    ]
