# Generated by Django 4.2.7 on 2023-11-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_alter_staffmovement_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='afternoon',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='night',
        ),
    ]
