# Generated by Django 4.1.12 on 2023-11-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_alter_salaryregister_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='sign',
            field=models.ImageField(upload_to='templates/signatures/'),
        ),
    ]
