# Generated by Django 4.1.12 on 2023-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0020_alter_salaryregister_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('Aid_no', models.IntegerField()),
                ('Age_gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('Date_Of_Admission', models.DateField()),
                ('Date_Of_Leaving', models.DateField()),
                ('Family_Contact_No', models.CharField(max_length=20)),
                ('Relation', models.CharField(max_length=50)),
                ('Permanent_Address', models.TextField()),
                ('Mode_Of_Identification_Rescue', models.CharField(max_length=100)),
                ('Identification_Mark', models.CharField(max_length=100)),
                ('Identification_Papers', models.CharField(max_length=100)),
                ('Rehabilitation_Measures', models.TextField()),
                ('Reason_For_Leaving_Shelter', models.TextField()),
                ('Follow_Up_Action', models.TextField()),
                ('Second_Follow_Up', models.TextField()),
                ('Medical_Status', models.CharField(max_length=50)),
                ('File_Closure_Status', models.CharField(max_length=50)),
                ('Remarks', models.TextField()),
                ('Signature', models.CharField(max_length=100)),
            ],
        ),
    ]
