# Generated by Django 4.2.7 on 2024-02-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0020_alter_accidentregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentregister',
            options={},
        ),
    ]
