# Generated by Django 4.1.12 on 2023-11-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0021_masterrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrecord',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='photos/'),
        ),
    ]
