# Generated by Django 4.2.7 on 2023-11-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0022_masterrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterRecord',
            new_name='MasterRecords',
        ),
    ]
