# Generated by Django 4.2.7 on 2024-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0022_actionplanregister_created_at_asset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterrecords',
            name='Action_takenup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
