# Generated by Django 4.1.12 on 2023-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0022_masterrecord_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecord',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
