# Generated by Django 4.2.7 on 2023-11-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0023_rename_masterrecord_masterrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
