# Generated by Django 4.1.12 on 2023-11-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0024_alter_masterrecord_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrecord',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='salaryregister',
            name='sign',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
