# Generated by Django 4.2.7 on 2024-02-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0024_remove_masterrecords_second_follow_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterrecords',
            old_name='Remarks',
            new_name='Fact_finding',
        ),
    ]
