# Generated by Django 4.2.7 on 2023-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0025_alter_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='photo',
        ),
        migrations.AddField(
            model_name='casehistory',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
