# Generated by Django 4.2.7 on 2024-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0025_rename_remarks_masterrecords_fact_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='what_dispossed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
