# Generated by Django 4.1.12 on 2023-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0025_alter_masterrecord_photo_alter_salaryregister_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='sign',
            field=models.ImageField(upload_to='media/signatures/'),
        ),
    ]
