# Generated by Django 4.2.7 on 2023-11-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0026_remove_casehistory_photo_casehistory_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='casehistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='case_history_photos/'),
        ),
    ]
