# Generated by Django 4.2.7 on 2024-02-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0026_asset_what_dispossed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='schoolFee',
            new_name='daysAbsent',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='dayOfPayment',
        ),
    ]
