# Generated by Django 4.2.7 on 2024-02-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0027_rename_schoolfee_resident_daysabsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabitation',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
