# Generated by Django 4.2.7 on 2023-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0027_remove_casehistory_photo_url_casehistory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
