# Generated by Django 4.1.12 on 2023-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0027_alter_salaryregister_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('participants', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='salaryregister',
            old_name='date_of_plan',
            new_name='date',
        ),
    ]
