# Generated by Django 4.1.12 on 2023-11-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0028_awarenessevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=50)),
                ('date_purchase', models.DateField()),
                ('name_asset', models.CharField(max_length=100)),
                ('no_of_items', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('bill_no', models.CharField(max_length=50)),
                ('place_asset', models.CharField(max_length=100)),
                ('owner_asset', models.CharField(max_length=100)),
                ('dispose_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='bppulsenote',
            name='bp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bppulsenote',
            name='sno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bppulsenote',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='policeMemoAvailable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='resident',
            name='schoolFee',
            field=models.IntegerField(),
        ),
    ]
