# Generated by Django 4.2.7 on 2024-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0028_rehabitation_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reintegration',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
