# Generated by Django 4.1.12 on 2023-11-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0029_asset_alter_bppulsenote_bp_alter_bppulsenote_sno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceappraisal',
            old_name='month',
            new_name='date',
        ),
    ]
