# Generated by Django 4.2.7 on 2023-11-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0029_remove_casehistory_photo_casehistory_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorregister',
            name='signature',
            field=models.TextField(),
        ),
    ]
