# Generated by Django 4.2.7 on 2023-11-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0030_alter_visitorregister_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffAttendence',
            new_name='StaffAttendance',
        ),
    ]
