# Generated by Django 4.1.12 on 2023-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0030_rename_month_performanceappraisal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceappraisal',
            name='beginning_children',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='death',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='end_strength',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='left',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='new_admission',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='referral',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='rehabilitation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='reintegration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='rescue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='total_strength',
            field=models.CharField(max_length=255),
        ),
    ]
