# Generated by Django 4.2.7 on 2023-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0031_rename_staffattendence_staffattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='remarks',
            field=models.TextField(),
        ),
    ]
