# Generated by Django 4.2.7 on 2024-02-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0032_alter_rehabitation_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='id',
            new_name='uqid',
        ),
    ]
