# Generated by Django 4.2.7 on 2023-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0032_alter_staffattendance_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='leave_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='sno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='working_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='working_hours',
            field=models.TimeField(),
        ),
    ]
