# Generated by Django 4.2.7 on 2023-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0033_alter_staffattendance_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='eveningAttendance',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='morningAttendance',
        ),
        migrations.AddField(
            model_name='resident',
            name='attendance',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='death',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='left',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='referral',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='rehabilitation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='reintegration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='rescue',
            field=models.CharField(max_length=255),
        ),
    ]
