# Generated by Django 4.2.7 on 2024-02-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0033_rename_id_casehistory_uqid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
