# Generated by Django 4.2.7 on 2024-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0034_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aid_no', models.CharField(max_length=100)),
                ('doa', models.DateField()),
                ('dol', models.DateField()),
                ('mode_of_rescue', models.CharField(max_length=100)),
                ('file_details', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('idnt_mark', models.CharField(max_length=255)),
                ('edu_back', models.CharField(max_length=255)),
                ('occcu_back', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('resident_ph', models.CharField(max_length=15)),
                ('relative_ph', models.CharField(max_length=15)),
                ('id_proof', models.CharField(max_length=100)),
                ('police_memo', models.CharField(max_length=100)),
                ('res_photo1', models.ImageField(upload_to='res_photos/')),
                ('res_photo2', models.ImageField(upload_to='res_photos/')),
                ('res_letter', models.FileField(upload_to='res_letters/')),
                ('small_narration', models.TextField()),
                ('genogram', models.ImageField(upload_to='genograms/')),
                ('res_family', models.CharField(max_length=255)),
                ('res_eco', models.CharField(max_length=255)),
                ('res_phy_status', models.CharField(max_length=255)),
                ('reason_for_homeless', models.TextField()),
                ('stre_and_weak', models.TextField()),
                ('fact', models.TextField()),
                ('rehab_measure', models.TextField()),
                ('action', models.TextField()),
            ],
        ),
    ]
