# Generated by Django 4.2.7 on 2023-11-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0034_remove_resident_eveningattendance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AwarnessRegister',
            new_name='AwarnesRegister',
        ),
    ]
