# Generated by Django 4.2.7 on 2023-11-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0036_alter_casehistory_address_alter_casehistory_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='educationBackground',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='idProofAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='idProofDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='identificationMark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='maritalStatus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='policeMemoAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='policeStationDetails',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='relativeOrFriendsContact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='religion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='residentContactNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
