# Generated by Django 4.2.7 on 2024-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0038_casework_genogram_phpto1_casework_genogram_phpto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casework',
            name='rehab_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='rehab_photo1/'),
        ),
        migrations.AddField(
            model_name='casework',
            name='rehab_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='rehab_photo2/'),
        ),
    ]
