# Generated by Django 4.2.7 on 2024-02-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0039_casework_rehab_photo1_casework_rehab_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='casework',
            name='uqid',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
