# Generated by Django 4.2.7 on 2024-02-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0040_casework_uqid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casework',
            old_name='genogram_phpto1',
            new_name='geno1',
        ),
        migrations.RenameField(
            model_name='casework',
            old_name='genogram_phpto2',
            new_name='geno2',
        ),
        migrations.RenameField(
            model_name='casework',
            old_name='reason_for_homeless_photo1',
            new_name='hl_photo1',
        ),
        migrations.RenameField(
            model_name='casework',
            old_name='reason_for_homeless_photo2',
            new_name='hl_photo2',
        ),
    ]
