# Generated by Django 4.2.7 on 2024-02-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0041_rename_genogram_phpto1_casework_geno1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casework',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
