# Generated by Django 4.2.7 on 2024-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0043_alter_casework_aid_no_alter_casework_genogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='casework',
            name='followup1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casework',
            name='followup2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casework',
            name='followup3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
