# Generated by Django 4.2.7 on 2024-02-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0044_casework_followup1_casework_followup2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterrecords',
            old_name='id',
            new_name='uqid',
        ),
    ]
