# Generated by Django 4.2.7 on 2024-02-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0045_rename_id_masterrecords_uqid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqid', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=100)),
                ('follow_up', models.TextField()),
                ('user', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
