# Generated by Django 4.2.7 on 2024-02-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0046_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='followup',
            name='uqid',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='followup',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
