# Generated by Django 4.2.7 on 2024-02-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0048_alter_followup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterrecords',
            name='Date_Of_Leaving',
        ),
    ]
