from django.contrib import admin

# Register your models here.
from .models import *
admin.site.register(provision)
admin.site.register(Rehabitation)
admin.site.register(MasterRecords)
admin.site.register(Reintegration)
admin.site.register(SalaryRegister)
admin.site.register(Inspectionregister)
admin.site.register(CaseHistory)
admin.site.register(MedicalCamp)
admin.site.register(Medicine)
admin.site.register(CounsellingRegister)
admin.site.register(BpPulsenote)
admin.site.register(AwarnesRegister)
admin.site.register(ActionplanRegister)
admin.site.register(SocialEntertainment)
admin.site.register(Resident)
admin.site.register(PerformanceAppraisal)
admin.site.register(VisitorRegister)
admin.site.register(Asset)
admin.site.register(FoodMenu)
admin.site.register(StaffMovement)
admin.site.register(PersonalInfo)
admin.site.register(AccidentRegister)
admin.site.register(Stock)
admin.site.register(EmploymentLink) 
admin.site.register(DeathRegister)
admin.site.register(NightSurvey)
admin.site.register(SkillTraining)
admin.site.register(SmcRegister)
admin.site.register(StaffAttendance)
admin.site.register(CaseWork)
admin.site.register(FollowUP)
